### ISSUE TITLE
Allow to plug a custom rule resolver 

### ISSUE THREAD

**Issue by lburgazzoli** [gnodet/mvnd#19]
As today to provide rules one has to create a property like:

```xml
<mvnd.builder.rule>
    camel-quarkus-core-xml-deployment,camel-quarkus-file-deployment,camel-quarkus-log-deployment,camel-quarkus-support-policy-deployment,camel-quarkus-timer-deployment
</mvnd.builder.rule>
```

Would be nice if mvnd would allow to plug a custom rule resolver so that there won't be the need to pollute poms.

As the example above is taken from camel-quarkus, one could develop a custom resolver that could compute the rules from the dependencies.

**Comment by gnodet** [comment]
I understand, but the rules are _in addition_ to dependency ordering.
That's mostly used in the cases the build is somewhat deficient and relies on the modules order defined in the `<modules>` section instead of relying on proper dependencies.
That said, I think an external file would be a good idea, something like a `mvnd.properties` file in the root directory of the project.

In general, a good alternative would be to fix the pom to have explicit dependencies instead of implicit dependencies defined by the modules order.

**Comment by ppalaga** [comment]
> That said, I think an external file would be a good idea, something like a `mvnd.properties` file in the root directory of the project.

This is not what @lburgazzoli asks for. He'd rather like an SPI for plugging in a custom piece of code that can produce the missing rules on demand.

In case Camel Quarkus and Quarkus, any form of hard coded rules will get outdated when there is a change in the dependencies of the itest. Having a dynamic lookup for that would avoid the maintenance costs. Moreover, the dynamic lookup implentation could perhaps be the same for Camel Quarkus, Quarkus and any other project having Quarkus extensions and their itests in the same source tree.

> In general, a good alternative would be to fix the pom to have explicit dependencies instead of implicit dependencies defined by the modules order.

Yes, this should be preferred, but I am afraid that's not possible with Quarkus itests. The deployment modules are hidden by design and adding them would actually break the build.

**Comment by lburgazzoli** [comment]
@ppalaga thx for clarify the issue and btw it was not supposed to be sent as it did lack lot of contextual info.

@gnodet the origin of the issue is from [here](https://github.com/apache/camel-quarkus/pull/705#issuecomment-585615072)

**Comment by gnodet** [comment]
I see.  I rejected the pluggable rule at first glance as I saw it as a bad way to solve pom problems.  The reason is that we have the same kind of problems in `camel` main tree (where a bunch of modules should depend on all components).
I'll have a look at a pluggable rules producer.  I suppose a groovy script that would receive the `MavenProject` object as the input and produce a list of strings would be ok ?

**Comment by ppalaga** [comment]
> I suppose a groovy script that would receive the `MavenSession` or `MavenProject` object as the input and produce a list of strings would be ok ?

What a flexibility! Sounds much easier than having a proper jar available in a remote Maven repo.

**Comment by lburgazzoli** [comment]
> > I suppose a groovy script that would receive the `MavenSession` or `MavenProject` object as the input and produce a list of strings would be ok ?
> 
> What a flexibility! Sounds much easier than having a proper jar available in a remote Maven repo.

At some point, we'll end up with gradle :P

**Comment by ppalaga** [comment]
No, no, nobody asks for too much Gradle!

**Comment by ppalaga** [comment]
> I suppose a groovy script that would receive the `MavenSession` or `MavenProject` object as the input and produce a list of strings would be ok ?

Thinking of it again, for the particular case of Quarkus itests, it would be much more performant if the script is called just once for the whole source tree. Figuring out which modules in the source tree are extensions should be done just once.

**Comment by gnodet** [comment]
I added a way to provide a custom provider.
You need to provide either a script or a url to a script:
```
        <mvnd.builder.rules.provider.url>tooling/mvnd.rules.provider.groovy</mvnd.builder.rules.provider.url>
```
or
```
        <mvnd.builder.rules.provider.script><![CDATA[
        return """
            camel-quarkus-core-deployment,camel-quarkus-aws-*-deployment,camel-quarkus-log-deployment,camel-quarkus-timer-deployment -> camel-quarkus-integration-test-aws
            camel-quarkus-core-deployment,camel-quarkus-bean-deployment,camel-quarkus-direct-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-bean
            camel-quarkus-core-deployment,camel-quarkus-direct-deployment,camel-quarkus-core-xml-deployment -> camel-quarkus-integration-test-core-cdi
            camel-quarkus-core-deployment,camel-quarkus-core-cloud-deployment -> camel-quarkus-integration-test-core-impl
            camel-quarkus-core-deployment,camel-quarkus-csv-deployment,camel-quarkus-direct-deployment -> camel-quarkus-integration-test-csv
            camel-quarkus-core-deployment,camel-quarkus-infinispan-deployment,camel-quarkus-log-deployment,camel-quarkus-netty-http-deployment -> camel-quarkus-integration-test-infinispan
            camel-quarkus-core-deployment,camel-quarkus-jdbc-deployment,camel-quarkus-direct-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-jdbc
            camel-quarkus-core-deployment,camel-quarkus-mail-deployment,camel-quarkus-direct-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-mail
            camel-quarkus-core-deployment,camel-quarkus-microprofile-metrics-deployment,camel-quarkus-direct-deployment -> camel-quarkus-integration-test-microprofile-metrics
            camel-quarkus-core-deployment,camel-quarkus-netty-http-deployment,camel-quarkus-core-deployment -> camel-quarkus-integration-test-netty-http
            camel-quarkus-core-deployment,camel-quarkus-paho-deployment,camel-quarkus-direct-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-paho
            camel-quarkus-core-deployment,camel-quarkus-salesforce-deployment,camel-quarkus-direct-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-salesforce
            camel-quarkus-core-deployment,camel-quarkus-servlet-deployment,camel-quarkus-rest-deployment,camel-quarkus-core-cloud-deployment -> camel-quarkus-integration-test-servlet
            camel-quarkus-core-deployment,camel-quarkus-twitter-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-twitter
            camel-quarkus-core-deployment,camel-quarkus-zipfile-deployment,camel-quarkus-direct-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-zipfile
            camel-quarkus-core-deployment,camel-quarkus-controlbus-deployment,camel-quarkus-direct-deployment,camel-quarkus-timer-deployment,camel-quarkus-log-deployment -> camel-quarkus-integration-test-controlbus
            """
        ]]></mvnd.builder.rules.provider.script>
```
